[package]
name = "ddd_rust_physics_example"
version = "0.1.0"
authors = ["Daniel Sonne Lehnberg <doddy@doddy.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
physics2d = { path = "../physics2d" }
